server:
  port: 8000
spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://180.76.54.181:2181
  scan:
    base-packages: xyz.hlmy
  protocol:
    name: dubbo
    port: 20880
